version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-stretch-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-10-dependencies-{{ checksum "package-lock.json" }}

      - run: npm version
      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: node-10-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run test:unit

      - run: npm run build
      - run: tar -zcvf dist.tar.gz ./dist

      - run: npm run build-no-auth
      - run: tar -zcvf dist-no-auth.tar.gz ./dist-no-auth

      - store_artifacts:
          path: ~/repo/coverage

      - store_artifacts:
          path: ~/repo/dist.tar.gz
