version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-stretch-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-10-dependencies-{{ checksum "package-lock.json" }}

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: node-10-dependencies-{{ checksum "package-lock.json" }}

      #- run: npm run test
      - run: npm run build
        -
      - store_artifacts:
          path: ~/repo/dist
